namespace SchemaDiscovery.SqlServer;

public class Constants
{
    public const string SQL_GET_TABLES = @"
			SELECT 
				TABLE_SCHEMA, 
				TABLE_NAME
			FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_TYPE = 'BASE TABLE'
			ORDER BY TABLE_SCHEMA, TABLE_NAME
		";

    public const string SQL_GET_TABLE_COLUMNS = @"
			SELECT 
				col.COLUMN_NAME,
				col.ORDINAL_POSITION,
				col.IS_NULLABLE,
				col.DATA_TYPE,
				col.CHARACTER_MAXIMUM_LENGTH,
				ISNULL(col.NUMERIC_PRECISION, 0) AS NUMERIC_PRECISION,
				ISNULL(col.NUMERIC_SCALE, 0) AS NUMERIC_SCALE,
				kcu.CONSTRAINT_NAME,
				tcnt.CONSTRAINT_TYPE,
				CASE tcnt.CONSTRAINT_TYPE
					WHEN 'PRIMARY KEY' THEN 'YES'
					ELSE 'NO'
				END AS IS_PRIMARY_KEY,
				CASE COLUMNPROPERTY(OBJECT_ID(col.TABLE_NAME), col.COLUMN_NAME,'IsIdentity')
					WHEN 1 THEN 'YES'
					ELSE 'NO'
				END AS IS_IDENTITY
			FROM INFORMATION_SCHEMA.COLUMNS col
			LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
				ON 
					kcu.TABLE_SCHEMA = col.TABLE_SCHEMA
					AND kcu.TABLE_NAME = col.TABLE_NAME
					AND kcu.COLUMN_NAME = col.COLUMN_NAME
			LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tcnt
				ON 
					kcu.TABLE_SCHEMA = tcnt.TABLE_SCHEMA
					AND kcu.TABLE_NAME = tcnt.TABLE_NAME	
					AND tcnt.CONSTRAINT_TYPE = 'PRIMARY KEY'
			WHERE 
					col.TABLE_SCHEMA = @TABLE_SCHEMA
					AND col.TABLE_NAME = @TABLE_NAME		
			ORDER BY ORDINAL_POSITION
		";
}